name: GitHub Actions Test
run-name: Github actions test
on:
  schedule:
    - cron: "0 23 * * *"
      timezone: "America/Los_Angeles"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"
